# Generated by Django 5.2.6 on 2025-10-01 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RECRUITER', '0002_recruiterprofile'),
        ('USER', '0002_jobseekerprofile'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver_jobseeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='USER.jobseeker'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver_recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='RECRUITER.recruiterregister'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_jobseeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='USER.jobseeker'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='RECRUITER.recruiterregister'),
        ),
    ]
