# Generated by Django 5.2.6 on 2025-10-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatmessage_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver_jobseeker',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver_recruiter',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender_jobseeker',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender_recruiter',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room_name',
            field=models.CharField(default='default_room', max_length=255),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
