# Generated by Django 5.2.6 on 2025-10-05 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RECRUITER', '0002_recruiterprofile'),
        ('USER', '0002_jobseekerprofile'),
        ('chat', '0003_remove_chatmessage_receiver_jobseeker_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender_name',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='job_seeker_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='USER.jobseeker'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='recruiter_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RECRUITER.recruiterregister'),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_rooms', to='USER.jobseeker')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_rooms', to='RECRUITER.recruiterregister')),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom'),
        ),
    ]
