# Generated by Django 5.2.6 on 2025-09-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education_required',
            field=models.CharField(blank=True, help_text="E.g. Bachelor's in CS, MBA, or any qualification.", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='roles_and_responsibilities',
            field=models.TextField(blank=True, help_text='Add roles and responsibilities (separate by new lines).', null=True),
        ),
    ]
