# Generated by Django 5.2.6 on 2025-09-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0003_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
    ]
