# Generated by Django 5.2.6 on 2025-09-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0004_remove_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
