# Generated by Django 5.2.6 on 2025-10-03 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTOM_ADMIN', '0001_initial'),
        ('JOB', '0005_jobapplication_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='CUSTOM_ADMIN.category'),
        ),
    ]
