# Generated by Django 5.2.6 on 2025-10-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0006_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
    ]
