# Generated by Django 5.2.6 on 2025-10-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTOM_ADMIN', '0001_initial'),
        ('JOB', '0007_remove_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='CUSTOM_ADMIN.category'),
        ),
    ]
